/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx,mdx}',
    './src/**/*.{html,css}',
  ],
  safelist: [
    'bg-slate-50',
    'bg-white',
    'bg-slate-900',
    'bg-slate-900/90',
    'bg-slate-100',
    'bg-white/5',
    'bg-white/10',
    'bg-white/95',
    'bg-sky-50',
    'bg-sky-100',
    'bg-sky-600',
    'bg-sky-700',
    'bg-sky-700/80',
    'bg-slate-200',
    'text-white',
    'text-white/90',
    'text-white/80',
    'text-white/70',
    'text-white/60',
    'text-slate-900',
    'text-slate-700',
    'text-slate-600',
    'text-slate-500',
    'text-slate-400',
    'text-sky-600',
    'text-sky-700',
    'text-sky-500',
    'from-sky-700',
    'via-sky-600',
    'to-slate-900',
    'ring-slate-200',
    'border-white/10',
    'border-white/15',
    'border-white/30',
    'border-slate-200',
    'shadow-xl',
    'shadow-sm',
    'rounded-2xl',
    'rounded-3xl',
    'rounded-xl',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
